### ISSUE TITLE
vmware_vcenter plugin uses static buffer size

### ISSUE THREAD

**Issue by KonradSchieban** [observIQ/stanza-plugins#239]
The latest release of stanza introduces the field `max_buffer_size` for `tcp_input` operator. It looks like this parameter is not available for the vmware_vcenter plugin. Even after increasing the value max_buffer_size, we get the warning message in the logs:

{"level":"warn","timestamp":"2021-03-28T22:23:09.460Z","message":"Failed flushing chunk. Waiting before retry","error":"rpc error: code = InvalidArgument desc = Log entry with size 512.5K exceeds maximum size of 256.0K","wait_time":0.684216499}

**Comment by jsirianni** [comment]
This is a welcome addition and we will be moving forward with the linked PR. However, it does not resolve the error mentioned. The Google API is limited to 256.0K, therefor any entry larger than that will be rejected. I will be following up on that error with a separate issue and solution.

**Comment by KonradSchieban** [comment]
I think this can be closed after this merge: https://github.com/observIQ/stanza/pull/263

**Comment by jsirianni** [comment]
resolved https://github.com/observIQ/stanza-plugins/pull/238
