### ISSUE TITLE
Kubernetes plugin promotes json log field, but leaves text log field

### ISSUE THREAD

**Issue by andykellr** [observIQ/stanza-plugins#59]
https://github.com/observIQ/stanza-plugins/blob/394b2dd37d06163a648b12b4cc122b59ad76b700/plugins/kubernetes.yaml#L56

This block will promote `$record.log => $` if the log field contains json.

```
  # Attempt to parse nested JSON since the log appears to be JSON
  - id: nested_json_parser
    type: json_parser
    parse_from: $record.log
    output: container_regex_parser
```

However, if the log is text, the message is left at `$record.log`. I think it should be promoted consistently, json or not.

**Comment by jsirianni** [comment]
I believe this was resolved
